### ISSUE TITLE
Tags with white spaces don't work

### ISSUE THREAD

**Issue by buep** [Praqma/praqma.github.io#134]
Under stories, selection Atlassian Jira tag.
![screenshot from 2016-01-20 17 58 56](https://cloud.githubusercontent.com/assets/1579826/12456338/93d79608-bf9f-11e5-9539-cd21b917db62.png)

**Comment by buep** [comment]
Others of the search list items do not work either... like Warning pluign

**Comment by lakruzz** [comment]
Original title was: No such page, selecting http://www.praqma.com/stories/#Atlassian%20Jira

@buep: When referencing URL's don't mention them in the header, do it in either the description or a comment - they don't get marked up in the title.

**Comment by lakruzz** [comment]
This is a Firefox issue - Links work in Chrome and Safari - but not in Firefox - haven't tried IE

- [x] Chrome
- [x] Safari
- [ ] Firefox
- [ ] Internet Explorer

**Comment by lakruzz** [comment]
Also registered by @praqma-thi in #146

**Comment by lakruzz** [comment]
@illus0r: Here's what we will do:

search and replace white spaces with dashes, both when you generate pages, and when you link to them, so that:

http://www.praqma.com/stories/#Atlassian%20Jira (firefox)
http://www.praqma.com/stories/#Atlassian Jira (chrome)

becomes:

http://www.praqma.com/stories/#Atlassian-Jira

You dig?
